create TABLE IF NOT EXISTS e_similarities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a    BIGINT                      NOT NULL,
    event_b    BIGINT                      NOT NULL,
    score      DOUBLE PRECISION            NOT NULL,
    timestamp_ts  TIMESTAMP WITHOUT TIME ZONE NOT NULL

);

create TABLE IF NOT EXISTS u_actions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT                      NOT NULL,
    user_id      BIGINT                      NOT NULL,
    action_type  VARCHAR                     NOT NULL,
    timestamp_ts    TIMESTAMP WITHOUT TIME ZONE NOT NULL

);
