server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**

        - id: main-service
          uri: lb://main-service
          predicates:
#            - Path=/categories/**, /users/**, /events/**, /compilations/**
            - Path=/**




#        - id: shopping_cart_service_route
#          uri: lb://shopping-cart
#          predicates:
#            - Path=/shopping-cart/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
