server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: stats-server-route
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**

        - id: category-service-route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**, /categories/**

        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests/**

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
