spring:
  application:
    name: event-service
  config:
    import: "configserver:"
  cloud:
    config:
      # не загружать другие компоненты до получения конфигурации
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      # если config-server недоступен, нужно сделать несколько попыток подключиться
      retry:
        # используем случайный backoff между попытками
        use-random-policy: true
        # максимальный интервал, в течение которого делаем попытки (6000 миллисекунд = 6 сек) max-interval: 6000
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
