spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/event
    username: main
    password: main

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      database-platform: org.hibernate.dialect.PostgreSQLDialect

grpc:
  server:
    port: 0
    security:
      enabled: false

kafka:
  consumer:
    user-properties:
      bootstrap:
        servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value.deserializer: deserialization.UserActionDeserializer
      enable.auto.commit: false
      group.id: user.actions.analyze
      client.id: userActionConsumer

      topic.user-action: stats.user-actions.v1
      user-consume-attempt-timeout: 1000

    similarity-properties:
      bootstrap:
        servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value.deserializer: deserialization.EventSimilarityDeserializer
      enable.auto.commit: false
      group.id: similarity.analyze
      client.id: similarityConsumer

      topic.similarity: stats.events-similarity.v1
      similarity-consume-attempt-timeout: 1000

logging:
  level:
    org.apache.kafka.*: ERROR
